### ISSUE TITLE
Sorting on system codes table fails

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#138]
### Bug Description
sorting on admin dlg failing

```

TypeError: sort() takes at most 2 arguments (3 given) 
Traceback (most recent call last):
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NZGBplugin/LINZ/Widgets/ListModelConnector.py", line 339, in sort
    self._sortIndex()
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NZGBplugin/LINZ/Widgets/ListModelConnector.py", line 351, in _sortIndex
    self._index.sort(None, keyfunc, self._sortReverse)
TypeError: sort() takes at most 2 arguments (3 given)


```

#### Steps to Reproduce
* open the admib dlg (from QGS menu `plugins > gazetteer > administration functions`)
* open system codes tab
* sort table

**Comment by SPlanzer** [comment]
resolved
